### ISSUE TITLE
Does not work with gulp v4+

### ISSUE THREAD

**Issue by sfairgrieve** [american-geo/focus#1]

**Comment by sfairgrieve** [comment]
https://stackoverflow.com/questions/51098749/everytime-i-run-gulp-anything-i-get-a-assertion-error-task-function-must-be

**Comment by zhik** [comment]
the fix seems to be installing gulp-cli instead of gulp`npm install --global gulp-cli`

**Comment by zhik** [comment]
#3 tested and working with `gulp` , `gulp build:minify`, and `gulp lint:js` commands
